### ISSUE TITLE
Actions没有任务

### ISSUE THREAD

**Issue by Minscs** [libsgh/Tieba-Sign-Actions#1]
![0](https://user-images.githubusercontent.com/68373675/87651412-78d4a100-c785-11ea-8edc-733b5bb77893.png)
star触发了。。

**Comment by onedrive-x** [comment]
![Screenshot_20200717-093254](https://user-images.githubusercontent.com/53255535/87738709-969b1800-c810-11ea-99de-f1ae3b536747.jpg)
我去你的actions看了，执行了啊，注意下签到时间，0，7，16。如果需要更改请自行调整。

**Comment by libsgh** [comment]
定时签到是每天的，0点，7点，16点。如果有需要可以自行修改，我去你的actions里面看了下是执行的。
![Screenshot_20200717-093254](https://user-images.githubusercontent.com/25656088/87738945-1cb75e80-c811-11ea-9977-9d72736928f1.jpg)
