### ISSUE TITLE
pages貌似不会自动更新啊

### ISSUE THREAD

**Issue by STC214** [libsgh/Tieba-Sign-Actions#11]
老铁 这pages主页有什么需要注意的点么 它不更新

**Comment by libsgh** [comment]
github pages会缓存，这个也是为了加载速度的考虑，但是时间不会太长，签到时间是凌晨，早上起来看数据肯定都是新的了，微信或电报通知的结果也是新的。感觉影响不大，如果确实有立即刷新的需求，可以自行按照网上的方案做下修改：[stackoverflow](https://stackoverflow.com/questions/24851824/how-long-does-it-take-for-github-page-to-show-changes-after-changing-index-html)

**Comment by STC214** [comment]
不行呢 点三五次还是老的ID和头像。。。

**Comment by libsgh** [comment]
> 不行呢 点三五次还是老的ID和头像。。。

你指的更新是更新了签到的账号，而签到的还是旧账号？

**Comment by STC214** [comment]
> 
> 
> > 不行呢 点三五次还是老的ID和头像。。。
> 
> 你指的更新是更新了签到的账号，而签到的还是旧账号？

对的 客户端显示已经签到了 但是pages依然是之前的样子

**Comment by libsgh** [comment]
> > > 不行呢 点三五次还是老的ID和头像。。。
> > 
> > 
> > 你指的更新是更新了签到的账号，而签到的还是旧账号？
> 
> 对的 客户端显示已经签到了 但是pages依然是之前的样子

把你的github仓库地址发我 我看下

**Comment by STC214** [comment]
> 
> 
> > > > 不行呢 点三五次还是老的ID和头像。。。
> > > 
> > > 
> > > 你指的更新是更新了签到的账号，而签到的还是旧账号？
> > 
> > 
> > 对的 客户端显示已经签到了 但是pages依然是之前的样子
> 
> 把你的github仓库和pages地址发下，或是截下图...

已经用别的脚本了 action停用了。。
