### ISSUE TITLE
建议添加：签到结果详细信息

### ISSUE THREAD

**Issue by Ryanjiena** [libsgh/Tieba-Sign-Actions#4]
现有的贴吧签到结果只有结果数

- 总数
- 已签到数
- 补签数
- 异常数

建议添加签到的详细信息。例如

- 已签到的贴吧信息
- 补签的贴吧信息
- 异常的贴吧信息

**Comment by libsgh** [comment]
那就是想要所有贴吧签到信息呗，因为action最终结果是json文件，直接展示这些数据可能会暴露你的隐私。可以考虑增加一个选项。

**Comment by Ryanjiena** [comment]
对，就是所有贴吧签到信息。至于隐私问题，不要直接输出，使用 telegram bot 或者 Server酱发送通知就行。

**Comment by libsgh** [comment]
> 对，就是所有贴吧签到信息。至于隐私问题，不要直接输出，使用 telegram bot 或者 Server酱发送通知就行。

贴吧太多没办法发送，消息太大了，只能通过网页查看。我再考虑考虑如何解决隐私问题。

**Comment by libsgh** [comment]
已添加详情和server酱通知
